version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: 'rabbitmq-app'
    ports:
      - "5673:5672"
      - "15672:15672"
    networks:
      - backend
networks:
  backend:
    driver: bridge  