export enum MicroserviceEnum {
    MICRO_SERVICES = 'MICRO_SERVICES',
  }

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ORG_ADMIN = 'ORG_ADMIN',
  ORG_EMPLOYEE = 'ORG_EMPLOYEE',
  ORG_REQUESTER = 'ORG_REQUESTER',
  ORG_AGENT = 'ORG_AGENT',
}
  